### ISSUE TITLE
Exit code 22 with zip file link

### ISSUE THREAD

**Issue by HarukiGrande** [tonikelope/megadown#12]
```
root@harukigrande:~/megadown# bash megadown 'https://mega.nz/#!O4hUSDAA!kHg_cs59dTYqlc6pkYWIPtTIm63UhV_WxL_SvLh8r2o'

Reading link metadata...

Downloading Anime.zip [8.4 GB] ...

   0 B 0:00:00 [   0 B/s] [>                                                                                              ]  0%

Oooops, download failed! EXIT CODE (22)```

**Comment by tonikelope** [comment]
Hi. Files bigger than 5GB do not work with megadown due to bandwitdh restrictions from MEGA I plan to implement a system to allow downloading large files without PREMIUM accounts when i have some spare time.

Regards.

In the meantime I recommend you to use to download large MEGA files ->   https://github.com/tonikelope/megabasterd
